"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HideoutArea = void 0;
var HideoutArea;
(function (HideoutArea) {
    HideoutArea[HideoutArea["Vents"] = 0] = "Vents";
    HideoutArea[HideoutArea["Security"] = 1] = "Security";
    HideoutArea[HideoutArea["WaterCloset"] = 2] = "WaterCloset";
    HideoutArea[HideoutArea["Stash"] = 3] = "Stash";
    HideoutArea[HideoutArea["Generator"] = 4] = "Generator";
    HideoutArea[HideoutArea["Heating"] = 5] = "Heating";
    HideoutArea[HideoutArea["WaterCollector"] = 6] = "WaterCollector";
    HideoutArea[HideoutArea["MedStation"] = 7] = "MedStation";
    HideoutArea[HideoutArea["Kitchen"] = 8] = "Kitchen";
    HideoutArea[HideoutArea["RestSpace"] = 9] = "RestSpace";
    HideoutArea[HideoutArea["Workbench"] = 10] = "Workbench";
    HideoutArea[HideoutArea["IntelligenceCenter"] = 11] = "IntelligenceCenter";
    HideoutArea[HideoutArea["ShootingRange"] = 12] = "ShootingRange";
    HideoutArea[HideoutArea["Library"] = 13] = "Library";
    HideoutArea[HideoutArea["ScavCase"] = 14] = "ScavCase";
    HideoutArea[HideoutArea["Illumination"] = 15] = "Illumination";
    HideoutArea[HideoutArea["PlaceOfFame"] = 16] = "PlaceOfFame";
    HideoutArea[HideoutArea["AirFilteringUnit"] = 17] = "AirFilteringUnit";
    HideoutArea[HideoutArea["SolarPower"] = 18] = "SolarPower";
    HideoutArea[HideoutArea["BoozeGenerator"] = 19] = "BoozeGenerator";
    HideoutArea[HideoutArea["BitcoinFarm"] = 20] = "BitcoinFarm";
    HideoutArea[HideoutArea["ChristmasIllumination"] = 21] = "ChristmasIllumination";
})(HideoutArea = exports.HideoutArea || (exports.HideoutArea = {}));
