export declare enum HideoutArea {
    Vents = 0,
    Security = 1,
    WaterCloset = 2,
    Stash = 3,
    Generator = 4,
    Heating = 5,
    WaterCollector = 6,
    MedStation = 7,
    Kitchen = 8,
    RestSpace = 9,
    Workbench = 10,
    IntelligenceCenter = 11,
    ShootingRange = 12,
    Library = 13,
    ScavCase = 14,
    Illumination = 15,
    PlaceOfFame = 16,
    AirFilteringUnit = 17,
    SolarPower = 18,
    BoozeGenerator = 19,
    BitcoinFarm = 20,
    ChristmasIllumination = 21
}
